server :
    port: 2020

spring:
    application:
        name: auth-service
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/authorization
        username: postgres
        password: postgres
    jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        